version: '3'
services:
    jrcms:
        image: tardigraded/jrcms-private:latest
        restart: always
        build: ./
        ports:
            - "8090:8080"
        environment:
            - REDIS_HOST=redis
        links:
            - redis
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
